### ISSUE TITLE
Weird crash at Ganon during the "Master Sword flies away" cutscene

### ISSUE THREAD

**Issue by Yanis42** [HackerN64/HackerOoT#71]
idk why but this crashed on HackerOoT, might be GCC? Note that it crashed during my compression tests but yaz crashed too

**Comment by Yanis42** [comment]
turns out it happens on normal decomp too, this is definitely a GCC crash, I took that to decomp discord

**Comment by ariahiro64** [comment]
i think this is exclusive to young link

**Comment by Yanis42** [comment]
I figured it out since, it's an OoB DL issue, I fixed it somewhere but forgot to PR it apparently

**Comment by Yanis42** [comment]
wait nvm it was merged in dev lol, gonna close this
